In [1]:
# Installs and  imports
# pip install -q implicit
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix, save_npz, load_npz
import implicit
import os
import json
import time

### Configuration

In [4]:
USER_COL = "user"
ITEM_COL = "isbn"
RATING_COL = "rating"

MIN_USER_RATINGS = 5
MIN_ITEM_RATINGS = 5
MAX_USER_RATINGS = 300     # cap extreme power users
IMPLICIT_THRESHOLDS = [(8, 3.0), (6, 2.0), (4, 1.0)]  # rating→weight mapping
CLIP_TO_BINARY = False

USE_BM25 = True
BM25_K1 = 1.2
BM25_B  = 0.75

ALS_FACTORS = 128
ALS_REG     = 0.05
ALS_ITERS   = 20
ALS_USE_CG  = True
ALS_ALPHA   = 60.0

TOPK = 10
SAMPLED_NEG_K = 1000

### Load and preprocess

In [7]:
ratings_prepared_data = pd.read_csv("data/df_ratings_prepared.csv")
df = ratings_prepared_data[[USER_COL, ITEM_COL, RATING_COL]].copy()
df[USER_COL] = df[USER_COL].astype(str)
df[ITEM_COL] = df[ITEM_COL].astype(str)
df[RATING_COL] = pd.to_numeric(df[RATING_COL], errors="coerce")
df = df.dropna(subset=[RATING_COL])

# implicit weight mapping
def to_implicit_weight(x):
    for thr, w in IMPLICIT_THRESHOLDS:
        if x >= thr:
            return w
    return 0.0
df["val"] = df[RATING_COL].apply(to_implicit_weight).astype(np.float32)
df = df[df["val"] > 0]

# cap power users
def cap_user(dfu):
    if len(dfu) <= MAX_USER_RATINGS:
        return dfu
    return dfu.nlargest(MAX_USER_RATINGS, ["val", RATING_COL])
df = df.groupby(USER_COL, group_keys=False).apply(cap_user)

# iterative prune
def iterative_prune(x, min_u, min_i):
    last = -1
    while last != len(x):
        last = len(x)
        uc = x.groupby(USER_COL)[ITEM_COL].count()
        ic = x.groupby(ITEM_COL)[USER_COL].count()
        keep_u = uc[uc >= min_u].index
        keep_i = ic[ic >= min_i].index
        x = x[x[USER_COL].isin(keep_u) & x[ITEM_COL].isin(keep_i)]
    return x

df = iterative_prune(df, MIN_USER_RATINGS, MIN_ITEM_RATINGS)

# map to ids
ucat = pd.Categorical(df[USER_COL]); icat = pd.Categorical(df[ITEM_COL])
df["uid"] = ucat.codes.astype(np.int32)
df["iid"] = icat.codes.astype(np.int32)
uid2raw = pd.Series(ucat.categories, index=np.arange(len(ucat.categories)))
iid2raw = pd.Series(icat.categories, index=np.arange(len(icat.categories)))
n_users = int(df["uid"].max()) + 1
n_items = int(df["iid"].max()) + 1
print("Final dataset:", n_users, "users ×", n_items, "items, interactions=", len(df))

Final dataset: 6365 users × 7791 items, interactions= 100577

### Train/test split

In [9]:
def train_test_split_per_user(df_ui, holdout_per_user=1, seed=123):
    rng = np.random.default_rng(seed)
    x = df_ui.copy()
    x["_r"] = rng.random(len(x))
    x = x.sort_values(["uid", "_r"])
    x["idx"] = x.groupby("uid").cumcount()
    sizes = x.groupby("uid")["idx"].transform("max") + 1
    x["is_test"] = x["idx"] >= (sizes - holdout_per_user)
    train = x[~x["is_test"]][["uid","iid","val"]]
    test  = x[ x["is_test"]][["uid","iid","val"]]
    # drop users with <2 train interactions
    has2 = train.groupby("uid")["iid"].count()
    keep_u = has2[has2 >= 2].index
    return train[train["uid"].isin(keep_u)], test[test["uid"].isin(keep_u)]

train_df, test_df = train_test_split_per_user(df, holdout_per_user=1)
n_users_tr = int(train_df["uid"].max()) + 1
n_items_tr = int(train_df["iid"].max()) + 1

### Build train matrix + weighting

In [11]:
def build_R_ui(train_df, n_users, n_items, clip_binary=False):
    rows = train_df["uid"].to_numpy()
    cols = train_df["iid"].to_numpy()
    vals = train_df["val"].astype(np.float32).to_numpy()
    if clip_binary:
        vals = (vals > 0).astype(np.float32)
    return csr_matrix((vals, (rows, cols)), shape=(n_users, n_items), dtype=np.float32)

R_ui = build_R_ui(train_df, n_users_tr, n_items_tr, clip_binary=CLIP_TO_BINARY)

if USE_BM25:
    R_weighted = implicit.nearest_neighbours.bm25_weight(R_ui.T, K1=BM25_K1, B=BM25_B).T
else:
    R_weighted = implicit.nearest_neighbours.tfidf_weight(R_ui.T).T

C_iu = (R_weighted * ALS_ALPHA).T.tocsr()  # ITEM×USER

### Train ALS with factor swap

In [13]:
def train_als(C_item_user, factors=128, reg=0.05, iterations=20, use_cg=True, seed=42):
    model = implicit.als.AlternatingLeastSquares(
        factors=factors, regularization=reg, iterations=iterations,
        use_cg=use_cg, random_state=seed
    )
    model.fit(C_item_user, show_progress=False)

    # After fitting on ITEM×USER:
    items_f = model.user_factors.copy()   # (n_items, k)
    users_f = model.item_factors.copy()   # (n_users, k)

    # Swap to correct orientation
    model.user_factors = users_f
    model.item_factors = items_f

    return model, users_f, items_f

als_model, U_users, V_items = train_als(C_iu, ALS_FACTORS, ALS_REG, ALS_ITERS, ALS_USE_CG)

C:\Users\Lenovo\anaconda3\Lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning: Intel MKL BLAS is configured to use 10 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'MKL_NUM_THREADS=1' or by callng 'threadpoolctl.threadpool_limits(1, "blas")'. Having MKL use a threadpool can lead to severe performance issues
  check_blas_config()

### Align artifacts

In [15]:
R_train = C_iu.T.tocsr()  # users×items
N_USERS, N_ITEMS = R_train.shape
seen = [set(R_train[u].indices.tolist()) for u in range(N_USERS)]
item_pop = np.asarray(R_train.getnnz(axis=0)).astype(np.int32)
pop_rank = np.argsort(-item_pop)

assert U_users.shape[0] == N_USERS
assert V_items.shape[0] == N_ITEMS

### Recommender

In [17]:
def als_recommend_for_user(uid, topn=10, blend_pop=0.0):
    uid = int(uid)
    if uid < 0 or uid >= N_USERS or R_train[uid].nnz == 0:
        return []
    user_row = R_train[uid]
    filt = np.fromiter((i for i in seen[uid]), dtype=np.int32) if seen[uid] else np.empty(0, np.int32)

    item_ids, scores = als_model.recommend(
        userid=uid, user_items=user_row, N=max(topn*2, topn),
        filter_items=filt, filter_already_liked_items=False, recalculate_user=False
    )

    if blend_pop <= 0:
        return [(int(i), float(s)) for i, s in zip(item_ids[:topn], scores[:topn])]

    s = np.asarray(scores, dtype=np.float32)
    p = item_pop[item_ids].astype(np.float32)
    mm = lambda x: np.zeros_like(x) if x.max() <= x.min() else (x - x.min())/(x.max()-x.min())
    final = (1-blend_pop)*mm(s) + blend_pop*mm(p)
    order = np.argsort(-final)[:topn]
    return [(int(item_ids[i]), float(final[i])) for i in order]

def popularity_recommend_for_user(uid, topn=10):
    already = seen[uid]
    out = []
    for i in pop_rank:
        if i not in already:
            out.append((int(i), float(item_pop[i])))
            if len(out) >= topn: break
    return out

### Evaluation

In [19]:
gt = test_df.groupby("uid")["iid"].apply(set)
gt = gt[[0 <= u < N_USERS and R_train[u].nnz > 0 for u in gt.index]]

def recall_at_k(pred, truth, k=10):
    return len(set(pred[:k]) & truth)/len(truth) if truth else 0.0

def apk(pred, truth, k=10):
    if not truth: return 0.0
    score, hits = 0.0, 0
    for i, p in enumerate(pred[:k], 1):
        if p in truth:
            hits += 1; score += hits/i
    return score/min(len(truth), k)

def evaluate_all_items(gt_dict, topn=10, rec_fn=als_recommend_for_user):
    recalls, maps = [], []
    for uid in gt_dict.index:
        preds = [i for i,_ in rec_fn(uid, topn=topn)]
        truth = gt_dict[uid]
        recalls.append(recall_at_k(preds, truth, k=topn))
        maps.append(apk(preds, truth, k=topn))
    return np.mean(recalls), np.mean(maps)

def evaluate_sampled(gt_dict, topn=10, negatives=1000):
    rng = np.random.default_rng(42)
    recalls, maps = [], []
    for uid in gt_dict.index:
        truth = list(gt_dict[uid])
        if not truth: continue
        banned = seen[uid]
        cand = set(truth)
        while len(cand) < len(truth) + negatives:
            j = int(rng.integers(0, N_ITEMS))
            if j not in banned: cand.add(j)
        cand = np.fromiter(cand, dtype=np.int32)

        uvec = U_users[uid]
        scores = V_items[cand] @ uvec
        order = np.argsort(-scores)[:topn]
        preds = cand[order].tolist()

        recalls.append(recall_at_k(preds, set(truth), k=topn))
        maps.append(apk(preds, set(truth), k=topn))
    return np.mean(recalls), np.mean(maps)

als_r10, als_m10 = evaluate_all_items(gt, topn=TOPK)
pop_r10, pop_m10 = evaluate_all_items(gt, topn=TOPK, rec_fn=popularity_recommend_for_user)
samp_r10, samp_m10 = evaluate_sampled(gt, topn=TOPK, negatives=SAMPLED_NEG_K)
print("ALS:", als_r10, als_m10)
print("POP:", pop_r10, pop_m10)
print("SAMPLED:", samp_r10, samp_m10)

ALS: 0.07855459544383346 0.037184877616927896
POP: 0.02717989002356638 0.009776555817404206
SAMPLED: 0.18067556952081698 0.0950563598049851

### Saving the first Version

In [32]:
MODEL_DIR = "models/als_v0"
os.makedirs(MODEL_DIR, exist_ok=True)
np.save(f"{MODEL_DIR}/U_users.npy", U_users.astype(np.float32))
np.save(f"{MODEL_DIR}/V_items.npy", V_items.astype(np.float32))
save_npz(f"{MODEL_DIR}/R_train.npz", R_train.astype(np.float32))
uid2raw.to_frame("user_raw").to_csv(f"{MODEL_DIR}/uid2raw.csv", index_label="uid")
iid2raw.to_frame("isbn_raw").to_csv(f"{MODEL_DIR}/iid2raw.csv", index_label="iid")
with open(f"{MODEL_DIR}/meta.json","w") as f:
    json.dump({"factors": int(U_users.shape[1]), "topk": TOPK}, f)

# Load later
U_users = np.load(f"{MODEL_DIR}/U_users.npy")
V_items = np.load(f"{MODEL_DIR}/V_items.npy")
R_train = load_npz(f"{MODEL_DIR}/R_train.npz").tocsr()
uid2raw = pd.read_csv(f"{MODEL_DIR}/uid2raw.csv", index_col="uid")["user_raw"]
iid2raw = pd.read_csv(f"{MODEL_DIR}/iid2raw.csv", index_col="iid")["isbn_raw"]

als_loaded = implicit.als.AlternatingLeastSquares(factors=U_users.shape[1], iterations=1, use_cg=True)
als_loaded.user_factors = U_users.copy()
als_loaded.item_factors = V_items.copy()

### Adjusting Hyperparameters

In [35]:
# Narrow ranges around current good values
grid = {
    "factors": [128, 192, 256],
    "reg":     [0.04, 0.06, 0.08],
    "alpha":   [50.0, 70.0, 90.0],
    "iters":   [20, 28],
    "blend":   [0.00, 0.05, 0.10],   # optional popularity blend at inference
}

results = []
run_id = 0

def fit_and_eval(R_weighted, alpha, factors, reg, iters, blend):
    """
    Fits ALS on C_iu = alpha * R_weighted^T, swaps factors to (users, items),
    rebuilds aligned artifacts, then evaluates with your existing eval functions.
    Returns (als_r10, als_m10, samp_r10, samp_m10, train_time_s).
    """
    global als_model, U_users, V_items, R_train, N_USERS, N_ITEMS, seen, item_pop, pop_rank

    t0 = time.time()

    # Build confidence (ITEM×USER)
    C_try = (R_weighted * alpha).T.tocsr()

    # Train ALS
    model = implicit.als.AlternatingLeastSquares(
        factors=factors, regularization=reg, iterations=iters, use_cg=True, random_state=42
    )
    model.fit(C_try, show_progress=False)

    # Swap factors so .recommend() expects users in user_factors, items in item_factors
    items_f = model.user_factors.copy()   # (n_items, k)
    users_f = model.item_factors.copy()   # (n_users, k)
    model.user_factors = users_f
    model.item_factors = items_f

    # Bind globals for recommender/eval functions
    als_model = model
    U_users = users_f
    V_items = items_f
    R_train = C_try.T.tocsr()  # users×items
    N_USERS, N_ITEMS = R_train.shape
    seen = [set(R_train[u].indices.tolist()) for u in range(N_USERS)]
    item_pop = np.asarray(R_train.getnnz(axis=0)).astype(np.int32)
    pop_rank = np.argsort(-item_pop)

    # Local wrapper to pass blend
    def _als_rec_fn(uid, topn=TOPK):
        return als_recommend_for_user(uid, topn=topn, blend_pop=blend)

    # Evaluate
    als_r10, als_m10 = evaluate_all_items(gt, topn=TOPK, rec_fn=_als_rec_fn)

    # Sampled negatives via direct dot-product (independent of .recommend())
    rng = np.random.default_rng(42)
    recalls, maps = [], []
    for uid in gt.index:
        truth = list(gt[uid])
        if not truth: 
            continue
        banned = seen[uid]
        cand = set(truth)
        while len(cand) < len(truth) + SAMPLED_NEG_K:
            j = int(rng.integers(0, N_ITEMS))
            if j not in banned:
                cand.add(j)
        cand = np.fromiter(cand, dtype=np.int32)

        uvec = U_users[uid]                 # (k,)
        scores = V_items[cand] @ uvec       # (|cand|,)
        order = np.argsort(-scores)[:TOPK]
        preds = cand[order].tolist()

        recalls.append(recall_at_k(preds, set(truth), k=TOPK))
        maps.append(apk(preds, set(truth), k=TOPK))
    samp_r10, samp_m10 = float(np.mean(recalls)), float(np.mean(maps))

    t1 = time.time()
    return als_r10, als_m10, samp_r10, samp_m10, (t1 - t0)

# ---- Run the sweep
for k in grid["factors"]:
    for reg in grid["reg"]:
        for a in grid["alpha"]:
            for it in grid["iters"]:
                for blend in grid["blend"]:
                    run_id += 1
                    r_all, m_all, r_samp, m_samp, secs = fit_and_eval(R_weighted, a, k, reg, it, blend)
                    results.append((run_id, k, reg, a, it, blend, r_all, m_all, r_samp, m_samp, secs))
                    print(f"[{run_id:03d}] f={k:3} reg={reg:.3f} α={a:5.1f} it={it:2d} "
                          f"blend={blend:0.2f}  "
                          f"ALS R@{TOPK}={r_all:.4f} MAP@{TOPK}={m_all:.4f}  "
                          f"SAMP R@{TOPK}={r_samp:.4f} MAP@{TOPK}={m_samp:.4f}  "
                          f"time={secs:.1f}s")

# ---- Results table
res_cols = ["run","factors","reg","alpha","iters","blend_pop",
            f"ALS_R@{TOPK}", f"ALS_MAP@{TOPK}",
            f"SAMP_R@{TOPK}", f"SAMP_MAP@{TOPK}", "train_secs"]
res_df = pd.DataFrame(results, columns=res_cols)

# Top-10 by ALS Recall then MAP
display(res_df.sort_values([f"ALS_R@{TOPK}", f"ALS_MAP@{TOPK}"], ascending=[False, False]).head(10))

# Also show top-10 by ALS MAP if you care more about ranking quality
display(res_df.sort_values([f"ALS_MAP@{TOPK}", f"ALS_R@{TOPK}"], ascending=[False, False]).head(10))

[001] f=128 reg=0.040 α= 50.0 it=20 blend=0.00  ALS R@10=0.0792 MAP@10=0.0379  SAMP R@10=0.1818 MAP@10=0.0959  time=80.4s
[002] f=128 reg=0.040 α= 50.0 it=20 blend=0.05  ALS R@10=0.0801 MAP@10=0.0379  SAMP R@10=0.1818 MAP@10=0.0959  time=83.5s
[003] f=128 reg=0.040 α= 50.0 it=20 blend=0.10  ALS R@10=0.0804 MAP@10=0.0379  SAMP R@10=0.1818 MAP@10=0.0959  time=84.9s
[004] f=128 reg=0.040 α= 50.0 it=28 blend=0.00  ALS R@10=0.0798 MAP@10=0.0382  SAMP R@10=0.1860 MAP@10=0.0957  time=85.8s
[005] f=128 reg=0.040 α= 50.0 it=28 blend=0.05  ALS R@10=0.0803 MAP@10=0.0380  SAMP R@10=0.1860 MAP@10=0.0957  time=83.2s
[006] f=128 reg=0.040 α= 50.0 it=28 blend=0.10  ALS R@10=0.0801 MAP@10=0.0376  SAMP R@10=0.1860 MAP@10=0.0957  time=83.1s
[007] f=128 reg=0.040 α= 70.0 it=20 blend=0.00  ALS R@10=0.0776 MAP@10=0.0371  SAMP R@10=0.1780 MAP@10=0.0930  time=79.8s
[008] f=128 reg=0.040 α= 70.0 it=20 blend=0.05  ALS R@10=0.0778 MAP@10=0.0372  SAMP R@10=0.1780 MAP@10=0.0930  time=81.0s
[009] f=128 reg=0.040 α= 70.0 it=20 blend=0.10  ALS R@10=0.0773 MAP@10=0.0366  SAMP R@10=0.1780 MAP@10=0.0930  time=82.8s
[010] f=128 reg=0.040 α= 70.0 it=28 blend=0.00  ALS R@10=0.0797 MAP@10=0.0378  SAMP R@10=0.1819 MAP@10=0.0944  time=84.3s
[011] f=128 reg=0.040 α= 70.0 it=28 blend=0.05  ALS R@10=0.0795 MAP@10=0.0376  SAMP R@10=0.1819 MAP@10=0.0944  time=83.2s
[012] f=128 reg=0.040 α= 70.0 it=28 blend=0.10  ALS R@10=0.0797 MAP@10=0.0374  SAMP R@10=0.1819 MAP@10=0.0944  time=80.4s
[013] f=128 reg=0.040 α= 90.0 it=20 blend=0.00  ALS R@10=0.0737 MAP@10=0.0355  SAMP R@10=0.1745 MAP@10=0.0887  time=82.4s
[014] f=128 reg=0.040 α= 90.0 it=20 blend=0.05  ALS R@10=0.0746 MAP@10=0.0354  SAMP R@10=0.1745 MAP@10=0.0887  time=82.8s
[015] f=128 reg=0.040 α= 90.0 it=20 blend=0.10  ALS R@10=0.0751 MAP@10=0.0355  SAMP R@10=0.1745 MAP@10=0.0887  time=83.2s
[016] f=128 reg=0.040 α= 90.0 it=28 blend=0.00  ALS R@10=0.0779 MAP@10=0.0367  SAMP R@10=0.1791 MAP@10=0.0927  time=82.6s
[017] f=128 reg=0.040 α= 90.0 it=28 blend=0.05  ALS R@10=0.0782 MAP@10=0.0370  SAMP R@10=0.1791 MAP@10=0.0927  time=85.8s
[018] f=128 reg=0.040 α= 90.0 it=28 blend=0.10  ALS R@10=0.0770 MAP@10=0.0366  SAMP R@10=0.1791 MAP@10=0.0927  time=83.7s
[019] f=128 reg=0.060 α= 50.0 it=20 blend=0.00  ALS R@10=0.0793 MAP@10=0.0381  SAMP R@10=0.1832 MAP@10=0.0963  time=83.3s
[020] f=128 reg=0.060 α= 50.0 it=20 blend=0.05  ALS R@10=0.0797 MAP@10=0.0383  SAMP R@10=0.1832 MAP@10=0.0963  time=85.2s
[021] f=128 reg=0.060 α= 50.0 it=20 blend=0.10  ALS R@10=0.0790 MAP@10=0.0377  SAMP R@10=0.1832 MAP@10=0.0963  time=85.5s
[022] f=128 reg=0.060 α= 50.0 it=28 blend=0.00  ALS R@10=0.0798 MAP@10=0.0379  SAMP R@10=0.1855 MAP@10=0.0956  time=86.1s
[023] f=128 reg=0.060 α= 50.0 it=28 blend=0.05  ALS R@10=0.0793 MAP@10=0.0377  SAMP R@10=0.1855 MAP@10=0.0956  time=85.5s
[024] f=128 reg=0.060 α= 50.0 it=28 blend=0.10  ALS R@10=0.0793 MAP@10=0.0374  SAMP R@10=0.1855 MAP@10=0.0956  time=85.1s
[025] f=128 reg=0.060 α= 70.0 it=20 blend=0.00  ALS R@10=0.0773 MAP@10=0.0370  SAMP R@10=0.1771 MAP@10=0.0926  time=80.7s
[026] f=128 reg=0.060 α= 70.0 it=20 blend=0.05  ALS R@10=0.0771 MAP@10=0.0369  SAMP R@10=0.1771 MAP@10=0.0926  time=83.1s
[027] f=128 reg=0.060 α= 70.0 it=20 blend=0.10  ALS R@10=0.0782 MAP@10=0.0368  SAMP R@10=0.1771 MAP@10=0.0926  time=83.3s
[028] f=128 reg=0.060 α= 70.0 it=28 blend=0.00  ALS R@10=0.0786 MAP@10=0.0377  SAMP R@10=0.1821 MAP@10=0.0951  time=81.6s
[029] f=128 reg=0.060 α= 70.0 it=28 blend=0.05  ALS R@10=0.0782 MAP@10=0.0375  SAMP R@10=0.1821 MAP@10=0.0951  time=79.6s
[030] f=128 reg=0.060 α= 70.0 it=28 blend=0.10  ALS R@10=0.0789 MAP@10=0.0376  SAMP R@10=0.1821 MAP@10=0.0951  time=81.2s
[031] f=128 reg=0.060 α= 90.0 it=20 blend=0.00  ALS R@10=0.0729 MAP@10=0.0353  SAMP R@10=0.1717 MAP@10=0.0885  time=83.6s
[032] f=128 reg=0.060 α= 90.0 it=20 blend=0.05  ALS R@10=0.0732 MAP@10=0.0354  SAMP R@10=0.1717 MAP@10=0.0885  time=85.2s
[033] f=128 reg=0.060 α= 90.0 it=20 blend=0.10  ALS R@10=0.0738 MAP@10=0.0354  SAMP R@10=0.1717 MAP@10=0.0885  time=82.9s
[034] f=128 reg=0.060 α= 90.0 it=28 blend=0.00  ALS R@10=0.0778 MAP@10=0.0369  SAMP R@10=0.1778 MAP@10=0.0925  time=84.2s
[035] f=128 reg=0.060 α= 90.0 it=28 blend=0.05  ALS R@10=0.0779 MAP@10=0.0370  SAMP R@10=0.1778 MAP@10=0.0925  time=85.6s
[036] f=128 reg=0.060 α= 90.0 it=28 blend=0.10  ALS R@10=0.0775 MAP@10=0.0367  SAMP R@10=0.1778 MAP@10=0.0925  time=84.3s
[037] f=128 reg=0.080 α= 50.0 it=20 blend=0.00  ALS R@10=0.0787 MAP@10=0.0380  SAMP R@10=0.1822 MAP@10=0.0961  time=81.0s
[038] f=128 reg=0.080 α= 50.0 it=20 blend=0.05  ALS R@10=0.0797 MAP@10=0.0377  SAMP R@10=0.1822 MAP@10=0.0961  time=83.2s
[039] f=128 reg=0.080 α= 50.0 it=20 blend=0.10  ALS R@10=0.0795 MAP@10=0.0375  SAMP R@10=0.1822 MAP@10=0.0961  time=85.3s
[040] f=128 reg=0.080 α= 50.0 it=28 blend=0.00  ALS R@10=0.0797 MAP@10=0.0378  SAMP R@10=0.1829 MAP@10=0.0949  time=83.1s
[041] f=128 reg=0.080 α= 50.0 it=28 blend=0.05  ALS R@10=0.0801 MAP@10=0.0376  SAMP R@10=0.1829 MAP@10=0.0949  time=84.8s
[042] f=128 reg=0.080 α= 50.0 it=28 blend=0.10  ALS R@10=0.0800 MAP@10=0.0371  SAMP R@10=0.1829 MAP@10=0.0949  time=84.7s
[043] f=128 reg=0.080 α= 70.0 it=20 blend=0.00  ALS R@10=0.0759 MAP@10=0.0367  SAMP R@10=0.1756 MAP@10=0.0923  time=82.5s
[044] f=128 reg=0.080 α= 70.0 it=20 blend=0.05  ALS R@10=0.0757 MAP@10=0.0367  SAMP R@10=0.1756 MAP@10=0.0923  time=83.4s
[045] f=128 reg=0.080 α= 70.0 it=20 blend=0.10  ALS R@10=0.0753 MAP@10=0.0365  SAMP R@10=0.1756 MAP@10=0.0923  time=81.5s
[046] f=128 reg=0.080 α= 70.0 it=28 blend=0.00  ALS R@10=0.0789 MAP@10=0.0379  SAMP R@10=0.1821 MAP@10=0.0944  time=84.0s
[047] f=128 reg=0.080 α= 70.0 it=28 blend=0.05  ALS R@10=0.0784 MAP@10=0.0375  SAMP R@10=0.1821 MAP@10=0.0944  time=84.6s
[048] f=128 reg=0.080 α= 70.0 it=28 blend=0.10  ALS R@10=0.0787 MAP@10=0.0374  SAMP R@10=0.1821 MAP@10=0.0944  time=84.3s
[049] f=128 reg=0.080 α= 90.0 it=20 blend=0.00  ALS R@10=0.0732 MAP@10=0.0353  SAMP R@10=0.1708 MAP@10=0.0881  time=82.8s
[050] f=128 reg=0.080 α= 90.0 it=20 blend=0.05  ALS R@10=0.0735 MAP@10=0.0354  SAMP R@10=0.1708 MAP@10=0.0881  time=83.3s
[051] f=128 reg=0.080 α= 90.0 it=20 blend=0.10  ALS R@10=0.0735 MAP@10=0.0356  SAMP R@10=0.1708 MAP@10=0.0881  time=83.3s
[052] f=128 reg=0.080 α= 90.0 it=28 blend=0.00  ALS R@10=0.0770 MAP@10=0.0371  SAMP R@10=0.1783 MAP@10=0.0936  time=82.8s
[053] f=128 reg=0.080 α= 90.0 it=28 blend=0.05  ALS R@10=0.0775 MAP@10=0.0369  SAMP R@10=0.1783 MAP@10=0.0936  time=86.7s
[054] f=128 reg=0.080 α= 90.0 it=28 blend=0.10  ALS R@10=0.0771 MAP@10=0.0371  SAMP R@10=0.1783 MAP@10=0.0936  time=77.4s
[055] f=192 reg=0.040 α= 50.0 it=20 blend=0.00  ALS R@10=0.0826 MAP@10=0.0415  SAMP R@10=0.1788 MAP@10=0.0968  time=85.1s
[056] f=192 reg=0.040 α= 50.0 it=20 blend=0.05  ALS R@10=0.0820 MAP@10=0.0413  SAMP R@10=0.1788 MAP@10=0.0968  time=86.7s
[057] f=192 reg=0.040 α= 50.0 it=20 blend=0.10  ALS R@10=0.0822 MAP@10=0.0411  SAMP R@10=0.1788 MAP@10=0.0968  time=79.4s
[058] f=192 reg=0.040 α= 50.0 it=28 blend=0.00  ALS R@10=0.0855 MAP@10=0.0418  SAMP R@10=0.1813 MAP@10=0.0982  time=87.0s
[059] f=192 reg=0.040 α= 50.0 it=28 blend=0.05  ALS R@10=0.0852 MAP@10=0.0417  SAMP R@10=0.1813 MAP@10=0.0982  time=88.2s
[060] f=192 reg=0.040 α= 50.0 it=28 blend=0.10  ALS R@10=0.0848 MAP@10=0.0421  SAMP R@10=0.1813 MAP@10=0.0982  time=90.4s
[061] f=192 reg=0.040 α= 70.0 it=20 blend=0.00  ALS R@10=0.0786 MAP@10=0.0395  SAMP R@10=0.1771 MAP@10=0.0941  time=84.8s
[062] f=192 reg=0.040 α= 70.0 it=20 blend=0.05  ALS R@10=0.0790 MAP@10=0.0393  SAMP R@10=0.1771 MAP@10=0.0941  time=79.3s
[063] f=192 reg=0.040 α= 70.0 it=20 blend=0.10  ALS R@10=0.0800 MAP@10=0.0395  SAMP R@10=0.1771 MAP@10=0.0941  time=86.9s
[064] f=192 reg=0.040 α= 70.0 it=28 blend=0.00  ALS R@10=0.0822 MAP@10=0.0413  SAMP R@10=0.1794 MAP@10=0.0965  time=87.0s
[065] f=192 reg=0.040 α= 70.0 it=28 blend=0.05  ALS R@10=0.0826 MAP@10=0.0414  SAMP R@10=0.1794 MAP@10=0.0965  time=88.2s
[066] f=192 reg=0.040 α= 70.0 it=28 blend=0.10  ALS R@10=0.0822 MAP@10=0.0414  SAMP R@10=0.1794 MAP@10=0.0965  time=87.7s
[067] f=192 reg=0.040 α= 90.0 it=20 blend=0.00  ALS R@10=0.0762 MAP@10=0.0376  SAMP R@10=0.1708 MAP@10=0.0926  time=87.2s
[068] f=192 reg=0.040 α= 90.0 it=20 blend=0.05  ALS R@10=0.0770 MAP@10=0.0376  SAMP R@10=0.1708 MAP@10=0.0926  time=85.6s
[069] f=192 reg=0.040 α= 90.0 it=20 blend=0.10  ALS R@10=0.0775 MAP@10=0.0374  SAMP R@10=0.1708 MAP@10=0.0926  time=86.1s
[070] f=192 reg=0.040 α= 90.0 it=28 blend=0.00  ALS R@10=0.0787 MAP@10=0.0395  SAMP R@10=0.1777 MAP@10=0.0947  time=86.9s
[071] f=192 reg=0.040 α= 90.0 it=28 blend=0.05  ALS R@10=0.0795 MAP@10=0.0398  SAMP R@10=0.1777 MAP@10=0.0947  time=87.1s
[072] f=192 reg=0.040 α= 90.0 it=28 blend=0.10  ALS R@10=0.0795 MAP@10=0.0394  SAMP R@10=0.1777 MAP@10=0.0947  time=87.6s
[073] f=192 reg=0.060 α= 50.0 it=20 blend=0.00  ALS R@10=0.0820 MAP@10=0.0416  SAMP R@10=0.1785 MAP@10=0.0967  time=385.7s
[074] f=192 reg=0.060 α= 50.0 it=20 blend=0.05  ALS R@10=0.0823 MAP@10=0.0416  SAMP R@10=0.1785 MAP@10=0.0967  time=35.4s
[075] f=192 reg=0.060 α= 50.0 it=20 blend=0.10  ALS R@10=0.0825 MAP@10=0.0414  SAMP R@10=0.1785 MAP@10=0.0967  time=53.7s
[076] f=192 reg=0.060 α= 50.0 it=28 blend=0.00  ALS R@10=0.0847 MAP@10=0.0419  SAMP R@10=0.1799 MAP@10=0.0986  time=85.5s
[077] f=192 reg=0.060 α= 50.0 it=28 blend=0.05  ALS R@10=0.0839 MAP@10=0.0419  SAMP R@10=0.1799 MAP@10=0.0986  time=88.2s
[078] f=192 reg=0.060 α= 50.0 it=28 blend=0.10  ALS R@10=0.0845 MAP@10=0.0421  SAMP R@10=0.1799 MAP@10=0.0986  time=93.1s
[079] f=192 reg=0.060 α= 70.0 it=20 blend=0.00  ALS R@10=0.0789 MAP@10=0.0396  SAMP R@10=0.1786 MAP@10=0.0949  time=82.9s
[080] f=192 reg=0.060 α= 70.0 it=20 blend=0.05  ALS R@10=0.0793 MAP@10=0.0396  SAMP R@10=0.1786 MAP@10=0.0949  time=79.9s
[081] f=192 reg=0.060 α= 70.0 it=20 blend=0.10  ALS R@10=0.0793 MAP@10=0.0395  SAMP R@10=0.1786 MAP@10=0.0949  time=92.0s
[082] f=192 reg=0.060 α= 70.0 it=28 blend=0.00  ALS R@10=0.0822 MAP@10=0.0411  SAMP R@10=0.1791 MAP@10=0.0968  time=85.0s
[083] f=192 reg=0.060 α= 70.0 it=28 blend=0.05  ALS R@10=0.0826 MAP@10=0.0413  SAMP R@10=0.1791 MAP@10=0.0968  time=87.6s
[084] f=192 reg=0.060 α= 70.0 it=28 blend=0.10  ALS R@10=0.0834 MAP@10=0.0413  SAMP R@10=0.1791 MAP@10=0.0968  time=88.0s
[085] f=192 reg=0.060 α= 90.0 it=20 blend=0.00  ALS R@10=0.0762 MAP@10=0.0375  SAMP R@10=0.1727 MAP@10=0.0920  time=86.1s
[086] f=192 reg=0.060 α= 90.0 it=20 blend=0.05  ALS R@10=0.0762 MAP@10=0.0376  SAMP R@10=0.1727 MAP@10=0.0920  time=87.4s
[087] f=192 reg=0.060 α= 90.0 it=20 blend=0.10  ALS R@10=0.0768 MAP@10=0.0378  SAMP R@10=0.1727 MAP@10=0.0920  time=86.1s
[088] f=192 reg=0.060 α= 90.0 it=28 blend=0.00  ALS R@10=0.0797 MAP@10=0.0396  SAMP R@10=0.1771 MAP@10=0.0946  time=85.7s
[089] f=192 reg=0.060 α= 90.0 it=28 blend=0.05  ALS R@10=0.0801 MAP@10=0.0395  SAMP R@10=0.1771 MAP@10=0.0946  time=86.8s
[090] f=192 reg=0.060 α= 90.0 it=28 blend=0.10  ALS R@10=0.0809 MAP@10=0.0398  SAMP R@10=0.1771 MAP@10=0.0946  time=87.9s
[091] f=192 reg=0.080 α= 50.0 it=20 blend=0.00  ALS R@10=0.0823 MAP@10=0.0410  SAMP R@10=0.1782 MAP@10=0.0970  time=86.1s
[092] f=192 reg=0.080 α= 50.0 it=20 blend=0.05  ALS R@10=0.0820 MAP@10=0.0412  SAMP R@10=0.1782 MAP@10=0.0970  time=86.4s
[093] f=192 reg=0.080 α= 50.0 it=20 blend=0.10  ALS R@10=0.0828 MAP@10=0.0414  SAMP R@10=0.1782 MAP@10=0.0970  time=87.2s
[094] f=192 reg=0.080 α= 50.0 it=28 blend=0.00  ALS R@10=0.0845 MAP@10=0.0416  SAMP R@10=0.1797 MAP@10=0.0985  time=87.3s
[095] f=192 reg=0.080 α= 50.0 it=28 blend=0.05  ALS R@10=0.0842 MAP@10=0.0416  SAMP R@10=0.1797 MAP@10=0.0985  time=89.6s
[096] f=192 reg=0.080 α= 50.0 it=28 blend=0.10  ALS R@10=0.0844 MAP@10=0.0416  SAMP R@10=0.1797 MAP@10=0.0985  time=88.6s
[097] f=192 reg=0.080 α= 70.0 it=20 blend=0.00  ALS R@10=0.0793 MAP@10=0.0397  SAMP R@10=0.1766 MAP@10=0.0943  time=84.6s
[098] f=192 reg=0.080 α= 70.0 it=20 blend=0.05  ALS R@10=0.0798 MAP@10=0.0397  SAMP R@10=0.1766 MAP@10=0.0943  time=81.8s
[099] f=192 reg=0.080 α= 70.0 it=20 blend=0.10  ALS R@10=0.0800 MAP@10=0.0397  SAMP R@10=0.1766 MAP@10=0.0943  time=85.9s
[100] f=192 reg=0.080 α= 70.0 it=28 blend=0.00  ALS R@10=0.0831 MAP@10=0.0411  SAMP R@10=0.1791 MAP@10=0.0967  time=86.1s
[101] f=192 reg=0.080 α= 70.0 it=28 blend=0.05  ALS R@10=0.0830 MAP@10=0.0410  SAMP R@10=0.1791 MAP@10=0.0967  time=86.3s
[102] f=192 reg=0.080 α= 70.0 it=28 blend=0.10  ALS R@10=0.0833 MAP@10=0.0411  SAMP R@10=0.1791 MAP@10=0.0967  time=89.2s
[103] f=192 reg=0.080 α= 90.0 it=20 blend=0.00  ALS R@10=0.0759 MAP@10=0.0377  SAMP R@10=0.1705 MAP@10=0.0918  time=81.9s
[104] f=192 reg=0.080 α= 90.0 it=20 blend=0.05  ALS R@10=0.0762 MAP@10=0.0379  SAMP R@10=0.1705 MAP@10=0.0918  time=84.2s
[105] f=192 reg=0.080 α= 90.0 it=20 blend=0.10  ALS R@10=0.0765 MAP@10=0.0381  SAMP R@10=0.1705 MAP@10=0.0918  time=86.9s
[106] f=192 reg=0.080 α= 90.0 it=28 blend=0.00  ALS R@10=0.0790 MAP@10=0.0391  SAMP R@10=0.1783 MAP@10=0.0949  time=88.6s
[107] f=192 reg=0.080 α= 90.0 it=28 blend=0.05  ALS R@10=0.0798 MAP@10=0.0392  SAMP R@10=0.1783 MAP@10=0.0949  time=87.4s
[108] f=192 reg=0.080 α= 90.0 it=28 blend=0.10  ALS R@10=0.0809 MAP@10=0.0394  SAMP R@10=0.1783 MAP@10=0.0949  time=87.7s
[109] f=256 reg=0.040 α= 50.0 it=20 blend=0.00  ALS R@10=0.0861 MAP@10=0.0442  SAMP R@10=0.1813 MAP@10=0.0986  time=194.7s
[110] f=256 reg=0.040 α= 50.0 it=20 blend=0.05  ALS R@10=0.0864 MAP@10=0.0441  SAMP R@10=0.1813 MAP@10=0.0986  time=201.8s
[111] f=256 reg=0.040 α= 50.0 it=20 blend=0.10  ALS R@10=0.0869 MAP@10=0.0441  SAMP R@10=0.1813 MAP@10=0.0986  time=191.4s
[112] f=256 reg=0.040 α= 50.0 it=28 blend=0.00  ALS R@10=0.0881 MAP@10=0.0437  SAMP R@10=0.1841 MAP@10=0.0989  time=256.8s
[113] f=256 reg=0.040 α= 50.0 it=28 blend=0.05  ALS R@10=0.0885 MAP@10=0.0439  SAMP R@10=0.1841 MAP@10=0.0989  time=253.6s
[114] f=256 reg=0.040 α= 50.0 it=28 blend=0.10  ALS R@10=0.0870 MAP@10=0.0437  SAMP R@10=0.1841 MAP@10=0.0989  time=243.6s
[115] f=256 reg=0.040 α= 70.0 it=20 blend=0.00  ALS R@10=0.0845 MAP@10=0.0422  SAMP R@10=0.1741 MAP@10=0.0961  time=188.7s
[116] f=256 reg=0.040 α= 70.0 it=20 blend=0.05  ALS R@10=0.0852 MAP@10=0.0425  SAMP R@10=0.1741 MAP@10=0.0961  time=209.3s
[117] f=256 reg=0.040 α= 70.0 it=20 blend=0.10  ALS R@10=0.0858 MAP@10=0.0426  SAMP R@10=0.1741 MAP@10=0.0961  time=205.5s
[118] f=256 reg=0.040 α= 70.0 it=28 blend=0.00  ALS R@10=0.0852 MAP@10=0.0432  SAMP R@10=0.1796 MAP@10=0.0981  time=266.3s
[119] f=256 reg=0.040 α= 70.0 it=28 blend=0.05  ALS R@10=0.0855 MAP@10=0.0433  SAMP R@10=0.1796 MAP@10=0.0981  time=267.9s
[120] f=256 reg=0.040 α= 70.0 it=28 blend=0.10  ALS R@10=0.0858 MAP@10=0.0436  SAMP R@10=0.1796 MAP@10=0.0981  time=259.7s
[121] f=256 reg=0.040 α= 90.0 it=20 blend=0.00  ALS R@10=0.0803 MAP@10=0.0408  SAMP R@10=0.1675 MAP@10=0.0914  time=205.2s
[122] f=256 reg=0.040 α= 90.0 it=20 blend=0.05  ALS R@10=0.0814 MAP@10=0.0410  SAMP R@10=0.1675 MAP@10=0.0914  time=214.2s
[123] f=256 reg=0.040 α= 90.0 it=20 blend=0.10  ALS R@10=0.0819 MAP@10=0.0408  SAMP R@10=0.1675 MAP@10=0.0914  time=203.3s
[124] f=256 reg=0.040 α= 90.0 it=28 blend=0.00  ALS R@10=0.0830 MAP@10=0.0423  SAMP R@10=0.1775 MAP@10=0.0963  time=237.4s
[125] f=256 reg=0.040 α= 90.0 it=28 blend=0.05  ALS R@10=0.0831 MAP@10=0.0424  SAMP R@10=0.1775 MAP@10=0.0963  time=246.1s
[126] f=256 reg=0.040 α= 90.0 it=28 blend=0.10  ALS R@10=0.0842 MAP@10=0.0425  SAMP R@10=0.1775 MAP@10=0.0963  time=248.4s
[127] f=256 reg=0.060 α= 50.0 it=20 blend=0.00  ALS R@10=0.0867 MAP@10=0.0436  SAMP R@10=0.1807 MAP@10=0.0980  time=46008.4s
[128] f=256 reg=0.060 α= 50.0 it=20 blend=0.05  ALS R@10=0.0866 MAP@10=0.0437  SAMP R@10=0.1807 MAP@10=0.0980  time=106.4s
[129] f=256 reg=0.060 α= 50.0 it=20 blend=0.10  ALS R@10=0.0875 MAP@10=0.0440  SAMP R@10=0.1807 MAP@10=0.0980  time=200.1s
[130] f=256 reg=0.060 α= 50.0 it=28 blend=0.00  ALS R@10=0.0891 MAP@10=0.0436  SAMP R@10=0.1822 MAP@10=0.0985  time=237.7s
[131] f=256 reg=0.060 α= 50.0 it=28 blend=0.05  ALS R@10=0.0892 MAP@10=0.0435  SAMP R@10=0.1822 MAP@10=0.0985  time=242.7s
[132] f=256 reg=0.060 α= 50.0 it=28 blend=0.10  ALS R@10=0.0880 MAP@10=0.0434  SAMP R@10=0.1822 MAP@10=0.0985  time=231.0s
[133] f=256 reg=0.060 α= 70.0 it=20 blend=0.00  ALS R@10=0.0839 MAP@10=0.0419  SAMP R@10=0.1725 MAP@10=0.0954  time=190.3s
[134] f=256 reg=0.060 α= 70.0 it=20 blend=0.05  ALS R@10=0.0844 MAP@10=0.0422  SAMP R@10=0.1725 MAP@10=0.0954  time=223.3s
[135] f=256 reg=0.060 α= 70.0 it=20 blend=0.10  ALS R@10=0.0845 MAP@10=0.0421  SAMP R@10=0.1725 MAP@10=0.0954  time=187.4s
[136] f=256 reg=0.060 α= 70.0 it=28 blend=0.00  ALS R@10=0.0863 MAP@10=0.0436  SAMP R@10=0.1800 MAP@10=0.0982  time=739.5s
[137] f=256 reg=0.060 α= 70.0 it=28 blend=0.05  ALS R@10=0.0861 MAP@10=0.0436  SAMP R@10=0.1800 MAP@10=0.0982  time=126.9s
[138] f=256 reg=0.060 α= 70.0 it=28 blend=0.10  ALS R@10=0.0863 MAP@10=0.0438  SAMP R@10=0.1800 MAP@10=0.0982  time=240.3s
[139] f=256 reg=0.060 α= 90.0 it=20 blend=0.00  ALS R@10=0.0798 MAP@10=0.0403  SAMP R@10=0.1679 MAP@10=0.0917  time=191.3s
[140] f=256 reg=0.060 α= 90.0 it=20 blend=0.05  ALS R@10=0.0804 MAP@10=0.0406  SAMP R@10=0.1679 MAP@10=0.0917  time=190.5s
[141] f=256 reg=0.060 α= 90.0 it=20 blend=0.10  ALS R@10=0.0815 MAP@10=0.0404  SAMP R@10=0.1679 MAP@10=0.0917  time=195.4s
[142] f=256 reg=0.060 α= 90.0 it=28 blend=0.00  ALS R@10=0.0825 MAP@10=0.0421  SAMP R@10=0.1752 MAP@10=0.0957  time=237.7s
[143] f=256 reg=0.060 α= 90.0 it=28 blend=0.05  ALS R@10=0.0826 MAP@10=0.0424  SAMP R@10=0.1752 MAP@10=0.0957  time=247.2s
[144] f=256 reg=0.060 α= 90.0 it=28 blend=0.10  ALS R@10=0.0828 MAP@10=0.0425  SAMP R@10=0.1752 MAP@10=0.0957  time=239.7s
[145] f=256 reg=0.080 α= 50.0 it=20 blend=0.00  ALS R@10=0.0870 MAP@10=0.0437  SAMP R@10=0.1802 MAP@10=0.0980  time=196.4s
[146] f=256 reg=0.080 α= 50.0 it=20 blend=0.05  ALS R@10=0.0872 MAP@10=0.0438  SAMP R@10=0.1802 MAP@10=0.0980  time=191.3s
[147] f=256 reg=0.080 α= 50.0 it=20 blend=0.10  ALS R@10=0.0874 MAP@10=0.0439  SAMP R@10=0.1802 MAP@10=0.0980  time=201.3s
[148] f=256 reg=0.080 α= 50.0 it=28 blend=0.00  ALS R@10=0.0892 MAP@10=0.0440  SAMP R@10=0.1827 MAP@10=0.0986  time=248.0s
[149] f=256 reg=0.080 α= 50.0 it=28 blend=0.05  ALS R@10=0.0899 MAP@10=0.0440  SAMP R@10=0.1827 MAP@10=0.0986  time=240.7s
[150] f=256 reg=0.080 α= 50.0 it=28 blend=0.10  ALS R@10=0.0888 MAP@10=0.0439  SAMP R@10=0.1827 MAP@10=0.0986  time=245.3s
[151] f=256 reg=0.080 α= 70.0 it=20 blend=0.00  ALS R@10=0.0831 MAP@10=0.0417  SAMP R@10=0.1725 MAP@10=0.0949  time=195.2s
[152] f=256 reg=0.080 α= 70.0 it=20 blend=0.05  ALS R@10=0.0837 MAP@10=0.0418  SAMP R@10=0.1725 MAP@10=0.0949  time=192.1s
[153] f=256 reg=0.080 α= 70.0 it=20 blend=0.10  ALS R@10=0.0842 MAP@10=0.0419  SAMP R@10=0.1725 MAP@10=0.0949  time=191.5s
[154] f=256 reg=0.080 α= 70.0 it=28 blend=0.00  ALS R@10=0.0848 MAP@10=0.0430  SAMP R@10=0.1794 MAP@10=0.0979  time=230.1s
[155] f=256 reg=0.080 α= 70.0 it=28 blend=0.05  ALS R@10=0.0848 MAP@10=0.0431  SAMP R@10=0.1794 MAP@10=0.0979  time=248.5s
[156] f=256 reg=0.080 α= 70.0 it=28 blend=0.10  ALS R@10=0.0848 MAP@10=0.0434  SAMP R@10=0.1794 MAP@10=0.0979  time=246.7s
[157] f=256 reg=0.080 α= 90.0 it=20 blend=0.00  ALS R@10=0.0801 MAP@10=0.0408  SAMP R@10=0.1667 MAP@10=0.0914  time=194.3s
[158] f=256 reg=0.080 α= 90.0 it=20 blend=0.05  ALS R@10=0.0811 MAP@10=0.0407  SAMP R@10=0.1667 MAP@10=0.0914  time=200.2s
[159] f=256 reg=0.080 α= 90.0 it=20 blend=0.10  ALS R@10=0.0814 MAP@10=0.0408  SAMP R@10=0.1667 MAP@10=0.0914  time=202.5s
[160] f=256 reg=0.080 α= 90.0 it=28 blend=0.00  ALS R@10=0.0825 MAP@10=0.0419  SAMP R@10=0.1750 MAP@10=0.0955  time=257.6s
[161] f=256 reg=0.080 α= 90.0 it=28 blend=0.05  ALS R@10=0.0828 MAP@10=0.0419  SAMP R@10=0.1750 MAP@10=0.0955  time=224.2s
[162] f=256 reg=0.080 α= 90.0 it=28 blend=0.10  ALS R@10=0.0831 MAP@10=0.0421  SAMP R@10=0.1750 MAP@10=0.0955  time=269.2s

,run,factors,reg,alpha,iters,blend_pop,ALS_R@10,ALS_MAP@10,SAMP_R@10,SAMP_MAP@10,train_secs
148,149,256,0.08,50.0,28,0.05,0.089866,0.043999,0.182718,0.098602,240.678018
147,148,256,0.08,50.0,28,0.00,0.089238,0.043956,0.182718,0.098602,248.024609
130,131,256,0.06,50.0,28,0.05,0.089238,0.043497,0.182247,0.098485,242.699528
129,130,256,0.06,50.0,28,0.00,0.089081,0.043621,0.182247,0.098485,237.719887
149,150,256,0.08,50.0,28,0.10,0.088767,0.043872,0.182718,0.098602,245.315656
112,113,256,0.04,50.0,28,0.05,0.088452,0.043856,0.184132,0.098892,253.567242
111,112,256,0.04,50.0,28,0.00,0.088138,0.043733,0.184132,0.098892,256.809261
131,132,256,0.06,50.0,28,0.10,0.087981,0.043428,0.182247,0.098485,230.970328
128,129,256,0.06,50.0,20,0.10,0.087510,0.043950,0.180676,0.098027,200.106317
146,147,256,0.08,50.0,20,0.10,0.087353,0.043906,0.180204,0.097980,201.336193

,run,factors,reg,alpha,iters,blend_pop,ALS_R@10,ALS_MAP@10,SAMP_R@10,SAMP_MAP@10,train_secs
108,109,256,0.04,50.0,20,0.00,0.086096,0.044177,0.181304,0.098635,194.702066
110,111,256,0.04,50.0,20,0.10,0.086881,0.044107,0.181304,0.098635,191.407512
109,110,256,0.04,50.0,20,0.05,0.086410,0.044100,0.181304,0.098635,201.824246
148,149,256,0.08,50.0,28,0.05,0.089866,0.043999,0.182718,0.098602,240.678018
147,148,256,0.08,50.0,28,0.00,0.089238,0.043956,0.182718,0.098602,248.024609
128,129,256,0.06,50.0,20,0.10,0.087510,0.043950,0.180676,0.098027,200.106317
146,147,256,0.08,50.0,20,0.10,0.087353,0.043906,0.180204,0.097980,201.336193
149,150,256,0.08,50.0,28,0.10,0.088767,0.043872,0.182718,0.098602,245.315656
112,113,256,0.04,50.0,28,0.05,0.088452,0.043856,0.184132,0.098892,253.567242
145,146,256,0.08,50.0,20,0.05,0.087196,0.043845,0.180204,0.097980,191.270128

### Best overall (all-items) hit:
- `f=256, reg=0.08, α=50, it=28, blend=0.05 → R@10≈0.0899, MAP@10≈0.0440 (runs ~240–250s)`.


#### Very close runner-ups:

- `f=256, reg=0.06, α=50, it=28, blend=0.00/0.05 → R@10≈0.0891–0.0892, MAP@10≈0.0435–0.0436`.

Speed/quality trade-off: `f=192, reg=0.06, α=50, it=28, blend=0.10 → R@10≈0.0845, MAP@10≈0.0421 (~88s)`.

Patterns:

- `α=50` consistently best; `α=90` consistently worse.
- Increasing factors improve performance but slows it down.
- `iters 28` gives small bumps vs 20.
- `blend 0.05–0.10` gives tiny MAP bumps; recall unchanged.

#### Recommendation 

**Quality-first (final):** `f=256, reg=0.08, α=50, it=28, blend=0.05`

**Speed-first variant:** `f=192, reg=0.06, α=50, it=28, blend=0.10`

### Saving the *better* model

In [42]:
# Params 
FINAL_FACTORS = 256
FINAL_REG     = 0.08
FINAL_ALPHA   = 50.0
FINAL_ITERS   = 28
FINAL_BLEND   = 0.05  # used only at inference

# Build confidence and fit
C_final = (R_weighted * FINAL_ALPHA).T.tocsr()  # item×user
final_model = implicit.als.AlternatingLeastSquares(
    factors=FINAL_FACTORS, regularization=FINAL_REG,
    iterations=FINAL_ITERS, use_cg=True, num_threads=os.cpu_count()
)
final_model.fit(C_final, show_progress=False)

# Swap factors so .recommend expects (users, items)
V_items = final_model.user_factors.copy()   # items
U_users = final_model.item_factors.copy()   # users
final_model.user_factors = U_users
final_model.item_factors = V_items

# Rebuild aligned inference artifacts
R_train = C_final.T.tocsr()  # users×items
N_USERS, N_ITEMS = R_train.shape
seen = [set(R_train[u].indices.tolist()) for u in range(N_USERS)]
item_pop = np.asarray(R_train.getnnz(axis=0)).astype(np.int32)
pop_rank = np.argsort(-item_pop)

def recommend_final(uid, topn=10):
    if uid < 0 or uid >= N_USERS or R_train[uid].nnz == 0:
        return []
    row = R_train[uid]
    filt = np.fromiter((i for i in seen[uid]), dtype=np.int32) if seen[uid] else np.empty(0, np.int32)
    ids, sc = final_model.recommend(uid, user_items=row, N=max(topn*2, topn),
                                    filter_items=filt, filter_already_liked_items=False, recalculate_user=False)
    if FINAL_BLEND <= 0:
        return [(int(i), float(s)) for i, s in zip(ids[:topn], sc[:topn])]
    s = np.asarray(sc, dtype=np.float32)
    p = item_pop[ids].astype(np.float32)
    def mm(x): 
        lo, hi = float(x.min()), float(x.max()); 
        return np.zeros_like(x) if hi<=lo else (x-lo)/(hi-lo)
    final = (1-FINAL_BLEND)*mm(s) + FINAL_BLEND*mm(p)
    order = np.argsort(-final)[:topn]
    return [(int(ids[i]), float(final[i])) for i in order]

# Save everything
MODEL_DIR = "models/als_best"
os.makedirs(MODEL_DIR, exist_ok=True)
np.save(f"{MODEL_DIR}/U_users.npy", U_users.astype(np.float32))
np.save(f"{MODEL_DIR}/V_items.npy", V_items.astype(np.float32))
save_npz(f"{MODEL_DIR}/R_train.npz", R_train.astype(np.float32))
uid2raw.to_frame("user_raw").to_csv(f"{MODEL_DIR}/uid2raw.csv", index_label="uid")
iid2raw.to_frame("isbn_raw").to_csv(f"{MODEL_DIR}/iid2raw.csv", index_label="iid")
with open(f"{MODEL_DIR}/meta.json","w") as f:
    json.dump({
        "factors": FINAL_FACTORS, "reg": FINAL_REG, "alpha": FINAL_ALPHA,
        "iters": FINAL_ITERS, "blend": FINAL_BLEND, "topk": TOPK
    }, f, indent=2)
print("Saved to", MODEL_DIR)

Saved to models/als_best